backend:
  name: git-gateway
  branch: main

media_folder: "public/assets"
public_folder: "/assets"

collections:
  - name: "blog"
    label: "部落格文章 (Blog)"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "標題 (Title)", name: "title", widget: "string" }
      - { label: "描述 (Description)", name: "description", widget: "string" }
      - { label: "發布日期 (PubDate)", name: "pubDate", widget: "datetime" }
      - { label: "更新日期 (UpdatedDate)", name: "updatedDate", widget: "datetime", optional: true }
      - { label: "封面圖片 (HeroImage)", name: "heroImage", widget: "image", optional: true }
      - { label: "內文 (Body)", name: "body", widget: "markdown" }

  - name: "showcase"
    label: "作品集 (Showcase)"
    folder: "src/content/showcase"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "標題 (Title)", name: "title", widget: "string" }
      - { label: "內文 (Body)", name: "body", widget: "markdown" }
