backend:
  name: git-gateway
  branch: master

media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"

collections:
  # --- 新增的區塊：頁面管理 ---
  - name: "pages"
    label: "頁面管理 (Pages)"
    files:
      - name: "home"
        label: "首頁內容"
        file: "public/content/pages/home.json"
        fields:
          - { label: "主標題", name: "hero_title", widget: "string" }
          - { label: "副標題", name: "hero_subtitle", widget: "string" }
          - { label: "說明文字", name: "hero_description", widget: "text" }
          - { label: "背景圖片", name: "hero_background_image", widget: "image" }

  # --- 我們原有的部落格和作品集設定 ---
  - name: "blog"
    label: "部落格文章 (Blog)"
    folder: "public/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "標題 (Title)", name: "title", widget: "string" }
      - { label: "發布日期 (Date)", name: "date", widget: "datetime" }
      - { label: "內文 (Body)", name: "body", widget: "markdown" }

  - name: "showcase"
    label: "作品集 (Showcase)"
    folder: "public/content/showcase"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "標題 (Title)", name: "title", widget: "string" }
      - { label: "內文 (Body)", name: "body", widget: "markdown" }
