backend:
  name: git-gateway
  branch: master

media_folder: "public/assets"
public_folder: "/assets"

collections:
  - name: "pages"
    label: "測試頁面"
    folder: "public/content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "內文", name: "body", widget: "markdown" }
