backend:
  name: git-gateway
  branch: master

# 我們暫時移除 media_folder 和 public_folder 來排除變數

collections:
  - name: "test"
    label: "除錯測試"
    folder: "public/content/test" # 指向一個全新的、乾淨的路徑
    create: true
    fields:
      - { name: "title", label: "標題", widget: "string" }
